---

- name: install deCONZ dependencies
  apt:
    name:
      - libcap2-bin
      - libqt5core5a
      - libqt5network5
      - libqt5serialport5
      - libqt5sql5
      - libqt5websockets5
      - libqt5widgets5
      - sqlite3
    state: present
  tags:
    - deconz

- name: install wiringpi dependency
  apt:
    deb: "{{ deconz_wiringpi_deb_url }}"
    state: present
  tags:
    - deconz

- name: add deCONZ user
  user:
    name: "{{ deconz_user }}"
    home: "{{ deconz_dir }}"
    createhome: true
    comment: "deCONZ"
    groups:
      - dialout
  tags:
    - deconz

- name: install deCONZ
  apt:
    deb: "{{ deconz_deb_url }}"
    state: present
  notify:
    - restart deconz
  tags:
    - deconz

- name: remove deCONZ desktop file
  file:
    state: absent
    path: "/home/{{ ansible_ssh_user }}/.config/autostart/deCONZ.desktop"
  tags:
    - deconz

- name: create systemd deCONZ override directory
  file:
    path: /etc/systemd/system/deconz.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - deconz

- name: add systemd deCONZ override
  template:
    src: ".{{ item }}.j2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - /etc/systemd/system/deconz.service.d/override.conf
  notify:
    - restart deconz
  tags:
    - deconz

- name: remove unwanted deCONZ services
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /lib/systemd/system/deconz-init.service
    - /lib/systemd/system/deconz-update.service
    - /lib/systemd/system/deconz-wifi.service
  notify:
    - reload systemd
  tags:
    - deconz

- name: start deCONZ
  systemd:
    name: deconz
    state: started
    enabled: true
  tags:
    - deconz
